export const SAVESHIPPINGADDRESS_LOADING = 'SAVESHIPPINGADDRESS_LOADING'
export const SAVESHIPPINGADDRESS_SUCCESS = 'SAVESHIPPINGADDRESS_SUCCESS'
export const SAVESHIPPINGADDRESS_ERROR = 'SAVESHIPPINGADDRESS_ERROR' 

export const FLASHSALEEVENT_LOADING = 'FLASHSALEEVENT_LOADING'
export const FLASHSALEEVENT_SUCCESS = 'FLASHSALEEVENT_SUCCESS'
export const FLASHSALEEVENT_ERROR = 'FLASHSALEEVENT_ERROR'  