export const SAVESHIPPINGADDRESS_LOADING = 'SAVESHIPPINGADDRESS_LOADING'
export const SAVESHIPPINGADDRESS_SUCCESS = 'SAVESHIPPINGADDRESS_SUCCESS'
export const SAVESHIPPINGADDRESS_ERROR = 'SAVESHIPPINGADDRESS_ERROR'  