export const USERPROFILE_LOADING = 'USERPROFILE_LOADING'
export const USERPROFILE_SUCCESS = 'USERPROFILE_SUCCESS'
export const USERPROFILE_ERROR = 'USERPROFILE_ERROR'

export const SHIPPINGADDRESS_LOADING = 'SHIPPINGADDRESS_LOADING'
export const SHIPPINGADDRESS_SUCCESS = 'SHIPPINGADDRESS_SUCCESS'
export const SHIPPINGADDRESS_ERROR = 'SHIPPINGADDRESS_ERROR' 

export const WAREHOUSEINVENTORY_LOADING = 'WAREHOUSEINVENTORY_LOADING'
export const WAREHOUSEINVENTORY_SUCCESS = 'WAREHOUSEINVENTORY_SUCCESS'
export const WAREHOUSEINVENTORY_ERROR = 'WAREHOUSEINVENTORY_ERROR'

export const FLASHSALEEVENT_LOADING = 'FLASHSALEEVENT_LOADING'
export const FLASHSALEEVENT_SUCCESS = 'FLASHSALEEVENT_SUCCESS'
export const FLASHSALEEVENT_ERROR = 'FLASHSALEEVENT_ERROR'  