export const CART_LOADING = 'CART_LOADING'
export const CART_LOADED = 'CART_LOADED'
export const CART_ERROR = 'CART_ERROR'

export const UPDATE_CART_LOADING = 'UPDATE_CART_LOADING'
export const UPDATE_CART_LOADED = 'UPDATE_CART_LOADED'
export const UPDATE_CART_ERROR = 'UPDATE_CART_ERROR'